{
 "title": "K8S Compliance Report",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Clusters",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "_exists_:cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Activity Log",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 0 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "_exists_:activity",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Status",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "compliance.status.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:compliance AND compliance.status:WARN",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "compliance.status.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:compliance AND compliance.status:FAIL",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "compliance.status.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:compliance AND compliance.status:PASS",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "K8S Compliance",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "_exists_:compliance",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "K8S Resources",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "_exists_:resource",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}